* Presenting the narrative

- I am in my prime... 

- Goal is to  gain flexible and crazy career capital 

* Rough

how to come to the us? shoudl I come to the US


I think i can do more.


gaining career capital, not sure if where i am working is the place for this?

My simple idea
1. jump within netherlands gain ex and then move to other countries where I can kill!

2. do MIS / another masters

3. GMAT

* Jump options:

1. Management consultant at the big3 Mckensy, with GMAT/Management masters
2. Investment banking
2. DATA scientist after doing some bootcamp courses or just join a traineeship
3. SALes
4. Marketting
5. Join asml and find my way through different groups!
5b. Jump with Holland to a starting job or a traineeship and see where that takes you, atleast you will gain career capital

Making the jump to sales?



* What I want and What I am currently not!

+# Begin_Quote

Some of the best ways to gain career capital early on include:

Working in any organisation which has, or with any people who have, a
reputation for high performance e.g. top consultancy or technology
firms, or any work with a great mentor or team.  Undertaking certain
graduate studies, especially applied quantitative subjects like
economics, computer science and applied mathematics.  Anything that
gives you a valuable transferable skill e.g. programming, data
science, marketing.  Taking opportunities which allow you to achieve
impressive and socially valuable things e.g. founding an organisation,
doing anything at which you might excel.

+# End_Quote



* Questions to rajesh

How did you jump to sales? after a shop floor scene!


stay technical! enhance your skills! management as an opotion investment banking

Part time MBA?

Minimum work 4-5 years needed" according to rajesh

Sales do not do!

Marketting product managenment --> more money, start technicla, start company... give you skiulls similar to sales!


Look at end and come back! not bored of engineering, good with people ! flexible 

cannot Have  a broad direction! find pasasion! knwo somesort of probelm!



Rate your career options!


You cannot get rid of your back groynd???????!!!!!!!

Yes!  give some intervies!

scholorship no  in the US! Check with people ! INCARD working professionals! check NC do part time from a good cvollege!b

how many years! ISB--> GMAT 24 lakhs! --> part time! part sponsorship ! check on the ability to learn forever!

You need to knwo what you want to do!

Do you or not take your parents money ! Look at loansw possibility here!

Merges and aquisitions! Unless you have value to offer! Investment banking... mostly do research!


you will know businews of an industry !

jump in a sinlgle year... 


Working in a msall company not doing much why!!! atleast earn a lo t of monye and get more options!
ASML! Philips!

DS! area going to be in very high demand!


Amazon, goolge, Europe! take an inter company transfer!

India,.... to US and got greenb card! lot of people ahve done it.... intoor! 1 year green card!



Work for a big company! Find aoppor to go to US... Do part time MBA!


DS! get deeper! personal fit! start thinking! all  options sem to fit... get into something  personal fit!

* Friends? 


* jump
I moved out of engineering!

ability to convince people that you will move to sales!
